Cloud testapp
Otus-DevOps-2018-09/AlexeyKondratyev_infra pull request #6
Opened 2018-11-21 23:56 UTC by AlexeyKondratyev

# Выполнено ДЗ №3

 - [+] Основное ДЗ
 - [+] Задание со *

## В процессе сделано:
  - Зарегистрировался в GCP
  - Создал проект infra
  - Создал ВМ bastion
  - Создал ВМ someinteralhost
  - Создал ssh ключ в метаданных
  - Разобрался как использовать SSH Forwarding
  - Установил и настроил Pritunl
  - Создал доверенный сертификат через sslip.io и Let's Encrypt
  - Добавил файлы setupvpn.sh и cloud-bastion.ovpn в проект

## Как запустить проект:
 - Установить клиент OpenVPN и использовать конфиг из проекта
 
## Как проверить работоспособность:
 - Например, перейти по ссылке https://35.205.219.184.sslip.io
 - Ввести пароль указанный в задании

## PR checklist
 - [+] Выставил label с номером домашнего задания
 - [+] Выставил label с темой домашнего задания

2018-11-28 12:47 UTC, WeitBelou commented on .github/PULL_REQUEST_TEMPLATE.md
> + - [+] Основное ДЗ
+ лишние

И правильный синтаксис для github markdown:
```md
- [x]
```

2018-11-28 12:48 UTC, WeitBelou commented on .github/PULL_REQUEST_TEMPLATE.md
> +# Выполнено ДЗ №3
В шаблоне не должен меняться номер ДЗ

2018-11-28 12:49 UTC, grim-yawn requested changes
По заданию всё ок, но шаблон не должен меняться.

2018-11-29 16:34 UTC, AlexeyKondratyev commented
Залил правильный .github/PULL_REQUEST_TEMPLATE.md

2018-11-29 16:35 UTC, AlexeyKondratyev commented
@WeitBelou

2018-12-03 07:24 UTC, grim-yawn approved these changes
Всё ок, небольшая проблема: надо поправить ip инстанса в README чтобы он указывал на запущенный инстанс, после прохождения travis можно будет мёрджить.

2018-12-04 08:10 UTC, merged